apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-pipeline-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ssime-git/argocd-manifests.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true