apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ssime-git/ml-pipeline-manifests.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-pipeline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true